<?php
/**
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2016
 *
 * @link      https://www.github.com/janhuang
 * @link      http://www.fast-d.cn/
 */

namespace FastD\Test;

use FastD\Application;
use FastD\Testing\TestCase as BaseTesting;
use Psr\Http\Message\ResponseInterface;

class TestCase extends BaseTesting
{
    /**
     * @var Application
     */
    protected $app;

    public function setUp()
    {
        $this->app = new Application(getcwd());
    }

    public function response(ResponseInterface $response, $assert)
    {
        parent::response($response, json_encode($assert)); // TODO: Change the autogenerated stub
    }
}