flows:
  - name: default
    language: php
    version: 7.0.3
    env:
      - FLOW_PROJECT_PATH=./project_src
      - DB=mysql

    trigger:
      push:
        - develop
        - master
      pull_request: true

    steps:
      - name: Init
        plugin:
          name: php_init

      - name: MySQL
        plugin:
          name: mysql_database

      - name: 创建 DB
        scripts:
          - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

      - name: Git Clone
        plugin:
          name: git

      - name: Install
        failure: true
        plugin:
          name: php_install

      - name: Test
        scripts: 
          - cd $FLOW_CURRENT_PROJECT_PATH
          - phpunit --configuration phpunit_$DB.xml --coverage-text