tools:
    # external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    # php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [app, vendor, tests, src/Console, src/Processor.php]
filter:
    excluded_paths:
        - 'tests/*'
        - 'app/*'
build:
    project_setup:
        before:
            - pecl install swoole
            - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS ci;"
            - mysql -uroot -e 'CREATE TABLE `ci`.`hello` (`id` int(11) NOT NULL AUTO_INCREMENT,`content` varchar(255) NOT NULL,`user` varchar(255) NOT NULL,`created` datetime NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;'
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover