<?php
/**
 * Created by PhpStorm.
 * User: janhuang
 * Date: 16/5/7
 * Time: 下午12:19
 * Github: https://www.github.com/janhuang
 * Coding: https://www.coding.net/janhuang
 * SegmentFault: http://segmentfault.com/u/janhuang
 * Blog: http://segmentfault.com/blog/janhuang
 * Gmail: bboyjanhuang@gmail.com
 * WebSite: http://www.janhuang.me
 */

namespace WelcomeBundle\Exceptions;

use FastD\Debug\Exceptions\Http\HttpException;

class NotFoundException extends HttpException
{
    public function getStatusCode()
    {
        return 404;
    }

    public function getHeaders()
    {
        return parent::getHeaders(); // TODO: Change the autogenerated stub
    }

    public function getContent()
    {
        return 404;
    }
}