<?php
/**
 * Created by PhpStorm.
 * User: janhuang
 * Date: 15/12/11
 * Time: 下午2:58
 * Github: https://www.github.com/janhuang
 * Coding: https://www.coding.net/janhuang
 * SegmentFault: http://segmentfault.com/u/janhuang
 * Blog: http://segmentfault.com/blog/janhuang
 * Gmail: bboyjanhuang@gmail.com
 * WebSite: http://www.janhuang.me
 */

namespace FastD;

use FastD\Standard\Commands\BundleGeneratorCommand;
use FastD\Standard\Commands\AssetInstallCommand;
use FastD\Standard\Commands\ConfigCacheCommand;
use FastD\Standard\Commands\FdbDataSetCommand;
use FastD\Standard\Commands\RouteCacheCommand;
use FastD\Standard\Commands\FdbReflexCommand;
use FastD\Standard\Commands\FdbSchemaCommand;
use FastD\Standard\Commands\RouteDumpCommand;
use FastD\Standard\Commands\SwooleCommand;
use FastD\Standard\Commands\ProdCommand;
use FastD\Console\Console;

/**
 * Class AppConsole
 *
 * @package FastD\Framework\Kernel
 */
class AppConsole extends Console
{
    /**
     * @var App
     */
    protected $application;

    /**
     * AppConsole constructor.
     *
     * @param array $bootstrap
     */
    public function __construct(array $bootstrap)
    {
        $this->application = new App($bootstrap);

        $this->application->bootstrap();

        parent::__construct();

        $this->application->scanCommands($this);
    }

    /**
     * @return App
     */
    public function getApplication()
    {
        return $this->application;
    }

    /**
     * @return \FastD\Container\Container
     */
    public function getContainer()
    {
        return $this->application->getContainer();
    }

    /**
     * @return array
     */
    public function getDefaultCommands()
    {
        $defaultCommands = parent::getDefaultCommands(); // TODO: Change the autogenerated stub

        return array_merge($defaultCommands, [
            new AssetInstallCommand(),
            new RouteCacheCommand(),
            new RouteDumpCommand(),
            new FdbReflexCommand(),
            new FdbDataSetCommand(),
            new FdbSchemaCommand(),
            new BundleGeneratorCommand(),
            new SwooleCommand(),
            new ConfigCacheCommand(),
            new ProdCommand(),
        ]);
    }

    /**
     * @return string
     */
    public function getDefaultCommandName()
    {
        return 'list';
    }

    /**
     * Scan commands.
     *
     * @param Console $console
     * @return void
     */
    public function scanCommands(Console $console)
    {
        foreach ($this->getApplication()->getBundles() as $bundle) {
            $dir = $bundle->getRootPath() . '/Commands';
            if (!is_dir($dir)) {
                continue;
            }
            $finder = new Finder();
            foreach ($finder->in($dir)->name('*Command.php')->files() as $file) {
                $class = $bundle->getNamespace() . '\\Commands\\' . pathinfo($file, PATHINFO_FILENAME);
                $command = new $class();
                if ($command instanceof CommandAware) {
                    $command->setContainer($this->getContainer());
                    $console->addCommand($command);
                }
            }
        }
    }
}