<?php
/**
 * Created by PhpStorm.
 * User: janhuang
 * Date: 15/12/11
 * Time: 下午2:58
 * Github: https://www.github.com/janhuang
 * Coding: https://www.coding.net/janhuang
 * SegmentFault: http://segmentfault.com/u/janhuang
 * Blog: http://segmentfault.com/blog/janhuang
 * Gmail: bboyjanhuang@gmail.com
 * WebSite: http://www.janhuang.me
 */

namespace FastD\Core;

use FastD\Standard\Commands\AssetInstallCommand;
use FastD\Standard\Commands\BundleGeneratorCommand;
use FastD\Standard\Commands\ConfigCacheCommand;
use FastD\Standard\Commands\FdbDataSetCommand;
use FastD\Standard\Commands\RouteCacheCommand;
use FastD\Standard\Commands\FdbReflexCommand;
use FastD\Standard\Commands\FdbSchemaCommand;
use FastD\Standard\Commands\RouteDumpCommand;
use FastD\Standard\Commands\SwooleCommand;
use FastD\Standard\Commands\ProdCommand;
use FastD\Console\Console as Application;

/**
 * Class AppConsole
 *
 * @package FastD\Framework\Kernel
 */
class Console extends Application
{
    /**
     * @var AppKernelInterface
     */
    protected $application;

    /**
     * AppConsole constructor.
     *
     * @param AppKernel $appKernel
     */
    public function __construct(AppKernel $appKernel)
    {
        $this->application = $appKernel;

        $this->application->bootstrap();

        parent::__construct();

        $appKernel->scanCommands($this);
    }

    /**
     * @return AppKernelInterface
     */
    public function getKernel()
    {
        return $this->application;
    }

    /**
     * @return \FastD\Container\Container
     */
    public function getContainer()
    {
        return $this->application->getContainer();
    }

    /**
     * @return array
     */
    public function getDefaultCommands()
    {
        $defaultCommands = parent::getDefaultCommands(); // TODO: Change the autogenerated stub

        return array_merge($defaultCommands, [
            new AssetInstallCommand(),
            new RouteCacheCommand(),
            new RouteDumpCommand(),
            new FdbReflexCommand(),
            new FdbDataSetCommand(),
            new FdbSchemaCommand(),
            new BundleGeneratorCommand(),
            new SwooleCommand(),
            new ConfigCacheCommand(),
            new ProdCommand(),
        ]);
    }

    /**
     * @return string
     */
    public function getDefaultCommandName()
    {
        return 'list';
    }
}